import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import Transition from "@/components/ui/transition";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "Haruna Usman Bello's Portfolio",
    template: "%s | Haruna Usman Bello's Portfolio",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0f172a]`}
      >
        <Toaster closeButton />

        <Transition>
          <Theme>{children}</Theme>
        </Transition>
      </body>
    </html>
  );
}
